project:
  type: website
  output-dir: docs
  
execute:
  freeze: true #ensures code is shown but Never run on Github


website:
  title: "Bioinfomatics Analysis Hub"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Single-Cell"
        contents:
          - section: "single_cell"
            contents:
              - text: "scanpy_gpu_version"
                file: single_cell/gpu_scanpy.ipynb
              - text: "Standard_Single-Cell_Workflow"
                file: single_cell/single-cell.ipynb
              - text: "NSCLU-LUSC_Patient19_single_cell"
                file: single_cell/NSCLU-LUSC_Patient19_single_cell.ipynb
              - text: "Perturb-seq"
                file: single_cell/perturb-seq.ipynb

      - section: "Spatial_Transcriptomics"
        contents:
          - section: "10X Atera"
            contents: 
              - text: "Atera"
                file: spatial_transcriptomics/Atera.ipynb
          - section: "Xenium Image-based"
            contents:
              - text: "xenium"
                file: spatial_transcriptomics/Xenium/xenium.ipynb
          - section: "CosMx"
            contents:
              - text: "nanostring_CosMx"
                file: spatial_transcriptomics/CosMx/nanostring_CosMx.ipynb
          - section: "Visium"
            contents:
              - text: "NSCLU-LUSC_Patient19_tumor"
                file: spatial_transcriptomics/Visium/NSCLU-LUSC_Patient19_tumor.ipynb

      - section: "Proteomics"
        contents:
          - text: "Lunaphore_comet Image-based"
            file: proteomics/lunaphore_comet.ipynb

      - section: "Notes"
        contents:
          - text: "Quarto_GitHub_Action"
            file: notes/quarto_github_action.qmd
            
format:
  html:
    theme: cosmo
    toc: true
