project:
  type: website
  output-dir: docs
  
execute:
  freeze: true #ensures code is shown but Never run on Github


website:
  title: "Bioinfomatics Analysis Hub"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Single-Cell RNAseq"
        contents:
          - text: "single-cell workflow"
            file: single_cell/gpu_scanpy.ipynb

      - section: "Spatial_Transcriptomics"
        contents:
          - text: "10X Atera"
            file: spatial_transcriptomics/Atera.ipynb

format:
  html:
    theme: cosmo
    toc: true